import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service'; import { RedisService } from '../redis/redis.service';
@Injectable()
export class ConversationsService {
 constructor(private prisma:PrismaService,private redis:RedisService){}
 private shape(c:any){return{id:c.id,listingId:c.listingId,buyerId:c.buyerId,sellerId:c.sellerId,updatedAt:c.updatedAt,listing:c.listing?{id:c.listing.id,title:c.listing.title,status:c.listing.status,priceVnd:Number(c.listing.priceVnd)}:undefined}}
 async start(userId:string,listingId:string){const listing=await this.prisma.listing.findFirst({where:{id:listingId,status:{in:['ACTIVE','RESERVED']}}});if(!listing)throw new NotFoundException('LISTING_NOT_AVAILABLE');if(listing.sellerId===userId)throw new BadRequestException('OWN_LISTING_CHAT');const blocked=await this.prisma.userBlock.findFirst({where:{OR:[{blockerId:userId,blockedId:listing.sellerId},{blockerId:listing.sellerId,blockedId:userId}]}});if(blocked)throw new ForbiddenException('CONVERSATION_BLOCKED');const c=await this.prisma.conversation.upsert({where:{listingId_buyerId_sellerId:{listingId,buyerId:userId,sellerId:listing.sellerId}},create:{listingId,buyerId:userId,sellerId:listing.sellerId},update:{updatedAt:new Date()},include:{listing:true}});return this.shape(c)}
 async list(userId:string){const rows=await this.prisma.conversation.findMany({where:{OR:[{buyerId:userId},{sellerId:userId}]},include:{listing:true},orderBy:{updatedAt:'desc'},take:100});return rows.map(x=>this.shape(x))}
 async get(userId:string,id:string){const c=await this.prisma.conversation.findUnique({where:{id},include:{listing:true}});if(!c||![c.buyerId,c.sellerId].includes(userId))throw new NotFoundException('CONVERSATION_NOT_FOUND');return this.shape(c)}
 async messages(userId:string,id:string,limit=100){await this.get(userId,id);return this.prisma.message.findMany({where:{conversationId:id,deletedAt:null},select:{id:true,conversationId:true,senderId:true,body:true,createdAt:true,readAt:true},orderBy:{createdAt:'asc'},take:Math.min(Math.max(limit,1),200)})}
 async send(userId:string,id:string,body:string){const text=String(body||'').trim();if(!text||text.length>3000)throw new BadRequestException('MESSAGE_INVALID');const c=await this.prisma.conversation.findUnique({where:{id}});if(!c||![c.buyerId,c.sellerId].includes(userId))throw new NotFoundException('CONVERSATION_NOT_FOUND');const blocked=await this.prisma.userBlock.findFirst({where:{OR:[{blockerId:c.buyerId,blockedId:c.sellerId},{blockerId:c.sellerId,blockedId:c.buyerId}]}});if(blocked)throw new ForbiddenException('CONVERSATION_BLOCKED');const gate=await this.redis.hit(`chat:${userId}`,30,60);if(!gate.allowed)throw new BadRequestException('MESSAGE_RATE_LIMIT');const [m]=await this.prisma.$transaction([this.prisma.message.create({data:{conversationId:id,senderId:userId,body:text},select:{id:true,conversationId:true,senderId:true,body:true,createdAt:true,readAt:true}}),this.prisma.conversation.update({where:{id},data:{updatedAt:new Date()}})]);return m}
}
