import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { site } from '@/lib/site'

type PageData={title:string;description:string;html:string;noindex?:boolean}
const pages:Record<string,PageData>={
 'gioi-thieu':{title:'Giới thiệu ChoVot Pickleball',description:'Sứ mệnh và nguyên tắc vận hành của marketplace chuyên vợt pickleball ChoVot.',html:`<h2>ChoVot giải quyết vấn đề gì?</h2><p>Vợt pickleball mới và cũ đang được giao dịch phân tán qua shop, hội nhóm và tin nhắn cá nhân. ChoVot xây một nơi tập trung để người chơi tìm, so sánh, đăng bán và kiểm tra mức độ tin cậy của giao dịch.</p><h2>Ba nguyên tắc</h2><ul><li><strong>Người thật:</strong> hồ sơ mua/bán cần các lớp xác thực phù hợp.</li><li><strong>Vợt thật:</strong> tình trạng sản phẩm, serial, ảnh và chứng từ được tách khỏi xác thực danh tính.</li><li><strong>Giao dịch minh bạch:</strong> trạng thái đơn hàng, vận chuyển, khiếu nại và thanh toán phải có bằng chứng.</li></ul><h2>ChoVot không làm gì?</h2><p>ChoVot không coi một dấu tick là bảo đảm tuyệt đối. Mỗi lớp xác thực chỉ giảm một nhóm rủi ro và phải được kết hợp với lịch sử giao dịch, bằng chứng sản phẩm và cơ chế xử lý tranh chấp.</p>`},
 'an-toan-giao-dich':{title:'An toàn giao dịch',description:'Cách ChoVot xác thực người dùng, cây vợt và bảo vệ luồng mua bán.',html:`<h2>Xác thực người và xác thực vợt là hai việc khác nhau</h2><p>Người bán có thể là người thật nhưng thông tin cây vợt vẫn có thể sai. Vì vậy ChoVot tách danh tính người dùng khỏi bằng chứng của sản phẩm.</p><h2>Luồng giao dịch đề xuất</h2><ol><li>Người mua và người bán đăng nhập/xác thực.</li><li>Tin đăng có ảnh thật, tình trạng, serial và chứng từ nếu có.</li><li>Thanh toán bảo vệ được xử lý bởi đối tác phù hợp; nền tảng không tự ý giữ tiền nếu chưa có cơ sở pháp lý và hạ tầng được phép.</li><li>Đơn hàng có tracking và trạng thái rõ.</li><li>Người mua kiểm tra trước khi xác nhận hoàn tất theo chính sách.</li></ol><h2>Thông tin nhạy cảm</h2><p>Không hiển thị công khai CCCD, dữ liệu sinh trắc học, số tài khoản đầy đủ hoặc token của nhà cung cấp KYC. Public profile chỉ hiển thị trạng thái xác thực và dữ liệu uy tín cần thiết.</p>`},
 'dieu-khoan':{title:'Điều khoản sử dụng',description:'Điều khoản cơ bản khi sử dụng ChoVot Pickleball.',noindex:true,html:`<h2>Phạm vi</h2><p>Điều khoản này là khung dự thảo cho giai đoạn xây dựng sản phẩm và cần được luật sư/đơn vị pháp lý rà soát trước khi mở giao dịch tiền thật.</p><h2>Trách nhiệm người dùng</h2><p>Người dùng phải cung cấp thông tin trung thực, không đăng hàng giả, hàng vi phạm quyền sở hữu trí tuệ, nội dung lừa đảo hoặc giao dịch trái pháp luật.</p><h2>Kiểm duyệt và khóa tài khoản</h2><p>ChoVot có quyền ẩn tin, yêu cầu bổ sung bằng chứng, tạm khóa hoặc chấm dứt tài khoản khi phát hiện dấu hiệu gian lận hoặc vi phạm chính sách.</p><h2>Thanh toán và tranh chấp</h2><p>Điều khoản thanh toán thực tế sẽ phụ thuộc đối tác thanh toán được tích hợp và phải được cập nhật trước ngày vận hành thương mại.</p>`},
 'chinh-sach-rieng-tu':{title:'Chính sách riêng tư',description:'Nguyên tắc thu thập, sử dụng và bảo vệ dữ liệu người dùng ChoVot.',noindex:true,html:`<h2>Dữ liệu chúng tôi cần</h2><p>Ở mức tối thiểu, hệ thống có thể xử lý thông tin tài khoản, trạng thái xác thực, tin đăng, hội thoại, đơn hàng và nhật ký bảo mật.</p><h2>Dữ liệu KYC</h2><p>Ưu tiên dùng nhà cung cấp eKYC để nhận trạng thái/xác nhận thay vì tự lưu ảnh CCCD hoặc dữ liệu sinh trắc học. Nếu có dữ liệu nhạy cảm bắt buộc phải lưu, cần mã hóa, giới hạn quyền truy cập và có chính sách lưu giữ/xóa rõ ràng.</p><h2>Chia sẻ dữ liệu</h2><p>Dữ liệu chỉ được chia sẻ cho bên xử lý cần thiết như KYC, thanh toán, vận chuyển hoặc cơ quan có thẩm quyền theo quy định áp dụng.</p>`},
 'ho-tro':{title:'Trung tâm hỗ trợ',description:'Hướng dẫn mua, bán, xác thực, giao hàng và xử lý tranh chấp trên ChoVot.',html:`<h2>Mua vợt</h2><p>Dùng bộ lọc marketplace, xem hồ sơ người bán, tình trạng vợt và bằng chứng sản phẩm trước khi đặt mua.</p><h2>Đăng bán</h2><p>Chuẩn bị ảnh mặt trước, mặt sau, viền, cán, serial và hóa đơn nếu có. Mô tả lỗi/va chạm rõ ràng.</p><h2>Xác thực</h2><p>Hoàn thành các bước xác thực theo yêu cầu của tài khoản. Không gửi giấy tờ nhạy cảm qua chat hoặc email hỗ trợ thông thường.</p><h2>Tranh chấp</h2><p>Lưu video mở hàng, ảnh kiện hàng, tracking và toàn bộ hội thoại trong nền tảng. Khiếu nại cần dựa trên bằng chứng, không chỉ mô tả bằng lời.</p>`}
}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug];if(!p)return{};return{title:p.title,description:p.description,alternates:{canonical:`/${slug}`},robots:p.noindex?{index:false,follow:true}:undefined}}
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}
export default async function InfoPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params,p=pages[slug];if(!p)notFound();const schema={'@context':'https://schema.org','@type':'WebPage',name:p.title,description:p.description,url:`${site.url}/${slug}`,inLanguage:'vi'};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="pageHero"><div className="container"><span className="eyebrow">ChoVot Pickleball</span><h1>{p.title}</h1><p>{p.description}</p></div></section><section className="section"><article className="container prose" dangerouslySetInnerHTML={{__html:p.html}}/></section></main>}
