export type Article={slug:string;title:string;description:string;updated:string;answer:string;html:string;keywords:string[]}

export const articles:Article[]=[
{
 slug:'vot-pickleball-14mm-va-16mm',
 title:'Vợt Pickleball 14mm và 16mm: khác nhau thế nào, nên chọn loại nào?',
 description:'So sánh vợt pickleball 14mm và 16mm theo lực đánh, kiểm soát, cảm giác bóng, độ ổn định và đối tượng phù hợp.',
 updated:'2026-09-11',
 answer:'Nếu ưu tiên tốc độ, phản hồi nhanh và sức mạnh, 14mm thường dễ tạo cảm giác bóng bật hơn. Nếu ưu tiên kiểm soát, độ ổn định và cảm giác mềm hơn khi reset/dink, 16mm thường dễ chơi hơn. Tuy nhiên cấu trúc lõi, vật liệu mặt, trọng lượng và hình dáng cũng ảnh hưởng rất lớn, nên không nên chọn chỉ dựa vào độ dày.',
 keywords:['vợt pickleball 14mm','vợt pickleball 16mm','14mm hay 16mm'],
 html:`<h2>14mm và 16mm khác nhau ở đâu?</h2><p>Độ dày là một trong nhiều yếu tố ảnh hưởng đến cảm giác đánh. Vợt mỏng hơn thường cho phản hồi nhanh và trực tiếp hơn, trong khi vợt dày hơn thường tăng cảm giác ổn định và kiểm soát. Nhưng hai cây cùng 16mm vẫn có thể chơi rất khác nhau nếu khác lõi, mặt carbon, trọng lượng swing weight hoặc hình dáng.</p><table><thead><tr><th>Tiêu chí</th><th>14mm</th><th>16mm</th></tr></thead><tbody><tr><td>Cảm giác</td><td>Nhanh, trực tiếp</td><td>Êm, ổn định hơn</td></tr><tr><td>Power</td><td>Thường dễ tạo lực</td><td>Thường thiên kiểm soát</td></tr><tr><td>Dink/reset</td><td>Cần tay mềm hơn</td><td>Dễ kiểm soát hơn</td></tr><tr><td>Phù hợp</td><td>Người thích tốc độ, drive</td><td>Người ưu tiên control, all-court</td></tr></tbody></table><h2>Nên chọn 14mm khi nào?</h2><p>14mm phù hợp nếu bạn thích bóng đi nhanh, chủ động drive, counter và muốn cảm giác phản hồi tức thì. Người đã có kỹ thuật kiểm soát lực tốt thường tận dụng được ưu điểm này rõ hơn.</p><h2>Nên chọn 16mm khi nào?</h2><p>16mm là lựa chọn an toàn cho nhiều người chơi vì dễ kiểm soát ở khu kitchen, reset bóng và giữ ổn định khi tiếp xúc không hoàn hảo. Nếu chưa biết chọn loại nào, 16mm thường là điểm bắt đầu hợp lý hơn.</p><h2>Đừng bỏ qua 4 thông số khác</h2><ul><li>Trọng lượng tổng và swing weight.</li><li>Hình dáng mặt vợt và chiều dài cán.</li><li>Vật liệu mặt và độ nhám tạo spin.</li><li>Cấu trúc lõi và phân bố sweet spot.</li></ul><h2>Kết luận nhanh</h2><p>Đừng xem 14mm là “power tuyệt đối” và 16mm là “control tuyệt đối”. Hãy dùng độ dày như một bộ lọc đầu tiên, sau đó so model cụ thể, tình trạng vợt và cảm giác thực tế.</p>`
},
{
 slug:'kiem-tra-vot-pickleball-cu',
 title:'Checklist kiểm tra vợt Pickleball cũ trước khi mua',
 description:'Checklist kiểm tra mặt vợt, viền, cán, lõi, serial, hóa đơn và lịch sử sử dụng khi mua vợt pickleball đã qua sử dụng.',
 updated:'2026-09-11',
 answer:'Khi mua vợt pickleball cũ, hãy kiểm tra ít nhất 6 nhóm: mặt vợt, viền, cán, âm thanh/lõi, serial/chứng từ và lịch sử sử dụng. Đừng chỉ nhìn phần trăm “95%” do người bán tự ghi; ảnh cận cảnh và bằng chứng nguồn gốc quan trọng hơn.',
 keywords:['mua vợt pickleball cũ','kiểm tra vợt pickleball cũ','vợt pickleball secondhand'],
 html:`<h2>1. Kiểm tra mặt vợt dưới ánh sáng xiên</h2><p>Yêu cầu ảnh rõ cả hai mặt. Quan sát vết trầy sâu, vùng bóng bất thường, bong lớp mặt hoặc dấu hiệu mài nhám. Các vết xước thẩm mỹ nhỏ không nhất thiết ảnh hưởng hiệu năng, nhưng hư hỏng cấu trúc cần được mô tả rõ.</p><h2>2. Kiểm tra viền và góc</h2><p>Viền là nơi dễ chịu va chạm khi người chơi quét sát mặt sân. Hãy xem kỹ các góc, cạnh trên và điểm nối giữa edge guard với thân vợt.</p><h2>3. Kiểm tra cán và grip</h2><p>Grip có thể thay mới, nhưng cán nứt, lỏng hoặc có dấu hiệu sửa chữa cần được coi là rủi ro cao hơn. Yêu cầu ảnh bỏ overgrip nếu cần xác minh tình trạng thực tế.</p><h2>4. Hỏi về lõi và âm thanh bất thường</h2><p>Nếu có điều kiện giao dịch trực tiếp, đánh thử vài bóng và lắng nghe âm thanh bất thường. Cảm giác rung, điểm chết rõ rệt hoặc tiếng lạ có thể là dấu hiệu cần kiểm tra thêm.</p><h2>5. Xác minh serial, NFC và hóa đơn</h2><p>Với model có serial/NFC, đối chiếu thông tin trên thân vợt với hộp, hóa đơn hoặc dữ liệu hãng nếu có. Serial giúp tăng độ tin cậy nhưng không nên được xem là bằng chứng duy nhất.</p><h2>6. Hỏi lịch sử sử dụng</h2><ul><li>Đã dùng bao lâu và tần suất bao nhiêu buổi/tuần?</li><li>Có từng va mạnh, sửa chữa hoặc thay edge guard không?</li><li>Có hóa đơn, hộp, phụ kiện hoặc bảo hành còn lại không?</li><li>Lý do bán là gì?</li></ul><h2>5 dấu hiệu nên thận trọng</h2><ul><li>Giá thấp bất thường so với các tin cùng model.</li><li>Chỉ có ảnh tổng thể, từ chối gửi ảnh cận cảnh.</li><li>Không giải thích được nguồn gốc/serial khi model vốn có serial.</li><li>Thúc ép chuyển khoản ngoài nền tảng.</li><li>Thông tin người bán mới tạo, không xác thực hoặc thay đổi liên tục.</li></ul><h2>Kết luận</h2><p>Mua vợt cũ tốt nhất khi thông tin tình trạng, danh tính người bán và bằng chứng sản phẩm được kiểm tra độc lập. ChoVot tách “xác thực người” và “xác thực cây vợt” thành hai lớp riêng vì một người thật vẫn có thể đăng thông tin sản phẩm sai.</p>`
},
{
 slug:'dinh-gia-vot-pickleball-cu',
 title:'Cách định giá vợt Pickleball cũ trước khi đăng bán',
 description:'Khung định giá vợt pickleball cũ dựa trên giá mới, độ mới, thời gian sử dụng, thanh khoản model, phụ kiện và chứng từ.',
 updated:'2026-09-11',
 answer:'Cách đơn giản nhất là bắt đầu từ giá bán mới thực tế của đúng model, rồi điều chỉnh theo tình trạng, thời gian sử dụng, thanh khoản, chứng từ và phụ kiện. Giá niêm yết không quan trọng bằng giá mà thị trường đang giao dịch.',
 keywords:['định giá vợt pickleball cũ','giá vợt pickleball cũ','bán vợt pickleball'],
 html:`<h2>Bước 1: Lấy giá mới thực tế, không chỉ giá niêm yết</h2><p>Nếu một model niêm yết 5 triệu nhưng các shop đang bán phổ biến 4,2 triệu, mốc tham chiếu nên gần 4,2 triệu hơn. Giá sale ngắn hạn có thể loại trừ nếu không đại diện cho thị trường.</p><h2>Bước 2: Chấm tình trạng theo bằng chứng</h2><p>Thay vì chỉ ghi “95%”, hãy mô tả cụ thể: mặt có xước không, edge guard có cấn không, cán/grip thế nào, serial và hóa đơn còn không. Hai cây cùng “95%” nhưng bằng chứng khác nhau có thể có giá rất khác.</p><h2>Bước 3: Tính thanh khoản của model</h2><p>Model đang phổ biến, nhiều người tìm mua và ít tin bán thường giữ giá tốt hơn. Model ít người biết hoặc phiên bản cũ phải có mức giá hấp dẫn hơn để đổi lấy tốc độ bán.</p><h2>Bước 4: Cộng/trừ phụ kiện và chứng từ</h2><table><thead><tr><th>Yếu tố</th><th>Tác động thường gặp</th></tr></thead><tbody><tr><td>Full box, hóa đơn, bảo hành</td><td>Tăng độ tin cậy và khả năng giữ giá</td></tr><tr><td>Không chứng từ</td><td>Cần giá hấp dẫn hơn nếu model có rủi ro hàng giả</td></tr><tr><td>Edge/cán có hư hỏng</td><td>Giảm giá theo mức ảnh hưởng thực tế</td></tr><tr><td>Model thanh khoản cao</td><td>Dễ bán gần giá kỳ vọng hơn</td></tr></tbody></table><h2>Ba mức giá nên dùng</h2><ul><li><strong>Giá bán nhanh:</strong> ưu tiên thanh khoản, chấp nhận thấp hơn một chút.</li><li><strong>Giá cân bằng:</strong> mức phù hợp với tình trạng và thị trường hiện tại.</li><li><strong>Giá chờ:</strong> cao hơn nhưng có thể mất nhiều thời gian tìm người mua.</li></ul><h2>Vì sao ChoVot cần dữ liệu giao dịch thật?</h2><p>Khi có đủ lịch sử giao dịch, định giá có thể dựa trên giá bán hoàn tất theo 30/60/90 ngày thay vì chỉ dựa trên tin đang rao. Điều này giảm tình trạng lấy một mức giá rao quá cao làm chuẩn.</p>`
}
]
export const getArticle=(slug:string)=>articles.find(a=>a.slug===slug)
