'use client'
import { FormEvent, useState } from 'react'
import { createSupabaseBrowserClient, hasSupabaseEnv } from '@/lib/supabase/client'

const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')

export default function SellPage(){
 const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[files,setFiles]=useState<File[]>([])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!hasSupabaseEnv()){setMsg('Backend Supabase chưa được cấu hình.');return}setBusy(true);setMsg('');const form=new FormData(e.currentTarget);const sb=createSupabaseBrowserClient();const {data:{user}}=await sb.auth.getUser();if(!user){setBusy(false);setMsg('Bạn cần đăng nhập trước khi đăng bán.');return}
  const {data:profile}=await sb.from('profiles').select('phone_verified,identity_verified,bank_verified').eq('id',user.id).maybeSingle();const verified=Boolean(profile?.phone_verified&&profile?.identity_verified&&profile?.bank_verified)
  const title=String(form.get('title')||'').trim();const price=Number(form.get('price')||0);const condition=String(form.get('condition')||'used');const slug=`${slugify(title)}-${Date.now().toString(36)}`
  const payload={seller_id:user.id,slug,title,brand:String(form.get('brand')||'').trim(),model:String(form.get('model')||'').trim(),condition,thickness_mm:Number(form.get('thickness_mm')||0)||null,price,location:String(form.get('location')||'').trim(),description:String(form.get('description')||'').trim(),serial_number:String(form.get('serial_number')||'').trim()||null,invoice_available:Boolean(form.get('invoice_available')),status:verified?'active':'draft'}
  const {data:listing,error}=await sb.from('listings').insert(payload).select('id,slug').single();if(error||!listing){setBusy(false);setMsg(error?.message||'Không thể tạo tin.');return}
  for(let i=0;i<files.length;i++){const f=files[i],ext=f.name.split('.').pop()?.toLowerCase()||'jpg',path=`${user.id}/${listing.id}/${i}-${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('listing-images').upload(path,f,{cacheControl:'3600',upsert:false});if(!up.error)await sb.from('listing_images').insert({listing_id:listing.id,storage_path:path,alt_text:`${title} - ảnh ${i+1}`,sort_order:i})}
  setBusy(false);setMsg(verified?'Đăng bán thành công. Tin đã xuất hiện trên marketplace.':'Tin đã lưu ở trạng thái nháp. Hoàn tất xác thực SĐT, danh tính và ngân hàng để công khai.')
  if(verified)setTimeout(()=>location.href=`/san-pham/${listing.slug}`,900)
 }
 return <main><section className="pageHero"><div className="container"><span className="eyebrow">Đăng bán có xác thực</span><h1>Đăng cây vợt của bạn</h1><p>Ảnh sản phẩm lưu trên Storage; tin chỉ được công khai khi hồ sơ người bán đáp ứng điều kiện xác thực.</p></div></section><section className="section"><div className="container" style={{maxWidth:820}}><form className="card" onSubmit={submit}><div className="grid" style={{gridTemplateColumns:'1fr 1fr'}}><label style={{gridColumn:'1/-1'}}><b>Tên sản phẩm *</b><input name="title" required placeholder="Ví dụ: Joola Perseus 16mm" style={input}/></label><label><b>Thương hiệu *</b><input name="brand" required placeholder="Joola" style={input}/></label><label><b>Model *</b><input name="model" required placeholder="Perseus" style={input}/></label><label><b>Tình trạng *</b><select name="condition" style={input}><option value="new">Mới 100%</option><option value="like_new">Like new</option><option value="excellent">Còn rất tốt</option><option value="used">Đã sử dụng</option></select></label><label><b>Độ dày</b><select name="thickness_mm" style={input}><option value="">Không rõ</option><option value="14">14mm</option><option value="16">16mm</option></select></label><label><b>Giá bán *</b><input name="price" type="number" min="1" required placeholder="2890000" style={input}/></label><label><b>Nơi giao dịch</b><input name="location" placeholder="TP.HCM / Hà Nội / Toàn quốc" style={input}/></label><label><b>Serial</b><input name="serial_number" placeholder="Nếu có" style={input}/></label><label style={{display:'flex',gap:8,alignItems:'center',paddingTop:30}}><input name="invoice_available" type="checkbox"/> Có hóa đơn/chứng từ</label><label style={{gridColumn:'1/-1'}}><b>Mô tả tình trạng</b><textarea name="description" rows={5} style={input} placeholder="Thời gian sử dụng, vết xước, phụ kiện đi kèm..."/></label><label style={{gridColumn:'1/-1'}}><b>Ảnh sản phẩm (tối đa 8 ảnh)</b><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple onChange={e=>setFiles([...e.target.files||[]].slice(0,8))} style={input}/><small>{files.length} ảnh đã chọn</small></label></div><button className="btn primary" disabled={busy} style={{marginTop:20}}>{busy?'Đang đăng...':'Đăng bán vợt'}</button>{msg&&<p className="answer">{msg}</p>}</form></div></section></main>
}
const input:React.CSSProperties={width:'100%',marginTop:7,padding:'12px 14px',border:'1px solid var(--line)',borderRadius:14,font:'inherit',background:'#fff'}
